### ISSUE TITLE
Do I need to generate frames of videos in advance to create the summaries?

### ISSUE THREAD

**Issue by running-machin** [590shun/video_summarization#1]
Hi, I am trying to follow the instructions in the read.md.

I have successfully able to train a sumgan model. I am trying to generate a video.  and used very similar args

`python summary.py -p logs/<timestamp>_<model_trainer_name>/<dataset_name>_splits.json_preds.h5 -f datasets/videos/summe/frames/Air_Force_One -d summarizer_dataset_summe_google_pool5.h5 -v video_1`
 that is 
 `python summary.py -p logs/1706525703_SumGANTrainer/summe_splits.json_preds.h5 -f datasets/videos/Air_Force_One -d summarizer_dataset_summe_google_pool5.h5 -v video_1  
`
I have an error 
`
global loadsave.cpp:248 findDecoder imread_('datasets/videos/Air_Force_One/001440.jpg'): can't open/read file: check file path/integrity
 32%|███████████▏                       | 1439/4494 [00:00<00:00, 509075.87it/s]
Traceback (most recent call last):
  File "summary.py", line 44, in <module>
    frm2video(args.frames, summary, vid_writer)
  File "summary.py", line 18, in frm2video
    frm = cv2.resize(frm, (args.width, args.height))
`

In the script above, u have `datasets/videos/summe/frames/Air_Force_One` if I am not wrong, You created the video frames of the video 'air_force_one'. If yes, how do I create it before generating the summary?

**Comment by running-machin** [comment]
Ok, I found it, I can use the `videos2frames.sh` that is in the videos folder to convert the vids to frames using ffmpeg, which is downloaded with the `summe.zip` dataset.
